# Generated by Django 6.0.3 on 2026-03-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Vacaciones', 'Vacaciones')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultorio',
            field=models.CharField(max_length=20),
        ),
    ]
