# Generated by Django 6.0.3 on 2026-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
