# Generated by Django 6.0.3 on 2026-03-29 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('doctores', '0002_doctor_estado_alter_doctor_consultorio'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='Completado', max_length=20)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
